package org.javai.springai.actions.tuning;

import org.javai.springai.actions.execution.ExecutablePlan;

public interface PlanQualityEvaluator {
	/**
	 * Evaluates the quality of a generated plan.
	 * @param userInput the original natural language request
	 * @param generatedQuery the DSL Query object generated by LLM
	 * @return a QualityScore containing multiple metrics
	 */
	PlanQualityScore evaluate(String userInput, ExecutablePlan generatedQuery);
}
