package org.javai.springai.actions.tuning;

/**
 * A variant of a system prompt, generated by a {@link SystemPromptVariationStrategy}.
 * 
 * @param systemPrompt the variant prompt text
 * @param rationale explanation of what makes this variant different from the baseline
 *                  (e.g., "Emphasizes safety guardrails" or "More concise")
 */
public record SystemPromptVariant(
		String systemPrompt,
		String rationale
) {}

